name: Update Proxies

on:
  schedule:
    # Runs every 2 minutes
    - cron: '*/2 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-proxies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests jq

      - name: Scrape and update proxies
        env:
          API_KEY: ${{ secrets.MY_API_KEY }}
        run: |
          PROXY_TYPES="http https socks4 socks5"
          API_URL="https://hex.qwezt.com:7000/api/v1/proxies/scrape"
          
          for type in $PROXY_TYPES
          do
            echo "Fetching $type proxies..."
            response=$(curl -s "$API_URL?proxy_type=$type&count=5000&apikey=$API_KEY")
            
            if [ "$(echo "$response" | jq -e '.proxies | length')" -gt 0 ]; then
              echo "$response" | jq -r '.proxies[] | "\(.ip):\(.port)"' > "${type}_proxies.txt"
              echo "Updated ${type}_proxies.txt"
            else
              echo "No $type proxies returned. Skipping file update."
            fi
          done

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add *.txt
          git commit -m "chore: Update proxy lists" || echo "No changes to commit"
          git push
