name: Update Proxies

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-proxies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Scrape and update proxies
        env:
          API_KEY: ${{ secrets.MY_API_KEY }}
        run: |
          set -e
          PROXY_TYPES="http https socks4 socks5"
          API_URL="https://hex.qwezt.com:7000/api/v1/proxies/scrape"
          
          for type in $PROXY_TYPES; do
            echo "--- Fetching proxies for $type ---"
            response=$(curl --connect-timeout 15 --max-time 30 -s -w "\nHTTP_STATUS:%{http_code}" "$API_URL?proxy_type=$type&count=5000&apikey=$API_KEY")
            http_status=$(echo "$response" | grep "HTTP_STATUS" | cut -d: -f2)
            body=$(echo "$response" | sed '$d')
            
            if [ "$http_status" -ne 200 ]; then
              echo "Error: Received HTTP status $http_status for $type. Skipping."
              continue
            fi
            
            if echo "$body" | jq -e '.proxies | length > 0' > /dev/null; then
              echo "$body" | jq -r '.proxies[] | "\(.ip):\(.port)"' > "${type}.txt"
              echo "Successfully updated ${type}.txt"
            else
              echo "No proxies found for $type. Creating an empty file."
              > "${type}.txt"
            fi
            echo "------------------------------------"
          done

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # ١. ابتدا آخرین تغییرات را از سرور دریافت می‌کنیم
          git pull --rebase origin main

          # ٢. سپس فایل‌های جدید را اضافه می‌کنیم
          git add *.txt
          
          # ٣. بررسی می‌کنیم که آیا تغییری برای کامیت وجود دارد یا نه
          if git diff --staged --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          
          # ٤. تغییرات را کامیت می‌کنیم
          git commit -m "chore(proxies): Update proxy lists"
          
          # ٥. در نهایت، به سرور push می‌کنیم
          git push
