name: Update Proxies

on:
  schedule:
    # Runs every 10 minutes to reduce concurrency issues
    - cron: '*/10 * * * *'
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  update-proxies:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # Fetch all history for proper git operations

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests jq

      - name: Scrape and update proxies
        env:
          API_KEY: ${{ secrets.MY_API_KEY }}
        run: |
          PROXY_TYPES="http https socks4 socks5"
          API_URL="https://hex.qwezt.com:7000/api/v1/proxies/scrape"
          
          for type in $PROXY_TYPES; do
            echo "Fetching $type proxies..."
            response=$(curl -s -f "$API_URL?proxy_type=$type&count=5000&apikey=$API_KEY")
            if [ $? -eq 0 ] && [ "$(echo "$response" | jq -e '.proxies | length')" -gt 0 ]; then
              echo "$response" | jq -r '.proxies[] | "\(.ip):\(.port)"' > "${type}_proxies.txt"
              echo "Updated ${type}_proxies.txt"
            else
              echo "Error fetching $type proxies or no proxies returned. Skipping file update."
            fi
          done

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add *.txt
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git pull --rebase origin main
          git commit -m "chore: Update proxy lists"
          git push https://x:${GITHUB_TOKEN}@github.com/hexmostafa/free-proxies.git
